hometasks/lesson15/twitter/config/routes.rb
Rails.application.routes.draw do
  root 'main#index'

  resources :users

  resources :twits do
    resources :comments
  end

  resources :tags

end

hometasks/lesson15/twitter/app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :user
  belongs_to :twit
  validates :body, presence: true
  validates :user, presence: true
end

hometasks/lesson15/twitter/app/models/tag.rb
class Tag < ActiveRecord::Base
  has_and_belongs_to_many :twits, join_table: 'tags_twits'
  acts_as_nested_set  dependent: :destroy,
                      counter_cache: :children_count
  validates :name, presence: true, uniqueness: true
end

hometasks/lesson15/twitter/app/models/twit.rb
class Twit < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  has_and_belongs_to_many :tags, join_table: 'tags_twits'
  validates :content, presence: true
  validates :user, presence: true
end

hometasks/lesson15/twitter/app/models/user.rb
class EmailValidator < ActiveModel::EachValidator
  def validate_each(record, attribute, value)
    unless value =~ /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
      record.errors[attribute] << (options[:message] || "is not an email")
    end
  end
end

class User < ActiveRecord::Base
  has_many :twits, dependent: :destroy
  has_many :comments
  validates :nickname, presence: true, uniqueness: {case_sensitive: false}, length: {minimum: 5}
  validates :email, presence: true, uniqueness: true, email: true
end

hometasks/lesson15/twitter/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

hometasks/lesson15/twitter/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @twit = Twit.find(params[:twit_id])
    @comment = @twit.comments.create(comment_params)
    redirect_to twit_path(@twit)
  end

  def destroy
    @twit = Twit.find(params[:twit_id])
    @comment = @twit.comments.find(params[:id])
    @comment.destroy
    redirect_to twit_path(@twit)
  end

  private
  def comment_params
    params.require(:comment).permit(:user_id, :body)
  end
end

hometasks/lesson15/twitter/app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

hometasks/lesson15/twitter/app/controllers/tags_controller.rb
class TagsController < ApplicationController
  before_action :set_tag, only: [:show, :edit, :update, :destroy]

  # GET /tags
  # GET /tags.json
  def index
    #@tags = Tag.nested_set_scope
    @tags = Tag.all
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
  end

  # GET /tags/new
  def new
    @tag = Tag.new
  end

  # GET /tags/1/edit
  def edit
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.create(tag_params)

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render :show, status: :created, location: @tag }
      else
        format.html { render :new }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tags/1
  # PATCH/PUT /tags/1.json
  def update
    respond_to do |format|
      if @tag.update(tag_params)
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { render :show, status: :ok, location: @tag }
      else
        format.html { render :edit }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to tags_url, notice: 'Tag was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_tag
    @tag = Tag.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def tag_params
    params.require(:tag).permit(:name, :parent_id)
  end
end

hometasks/lesson15/twitter/app/controllers/twits_controller.rb
class TwitsController < ApplicationController
  before_action :set_twit, only: [:show, :edit, :update, :destroy]

  # GET /twits
  # GET /twits.json
  def index
    @twits = Twit.all
  end

  # GET /twits/1
  # GET /twits/1.json
  def show
  end

  # GET /twits/new
  def new
    @twit = Twit.new
  end

  # GET /twits/1/edit
  def edit
  end

  # POST /twits
  # POST /twits.json
  def create
    @twit = Twit.new(twit_params)

    respond_to do |format|
      if @twit.save
        format.html { redirect_to @twit, notice: 'Twit was successfully created.' }
        format.json { render :show, status: :created, location: @twit }
      else
        format.html { render :new }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /twits/1
  # PATCH/PUT /twits/1.json
  def update
    respond_to do |format|
      if @twit.update(twit_params)
        format.html { redirect_to @twit, notice: 'Twit was successfully updated.' }
        format.json { render :show, status: :ok, location: @twit }
      else
        format.html { render :edit }
        format.json { render json: @twit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /twits/1
  # DELETE /twits/1.json
  def destroy
    @twit.destroy
    respond_to do |format|
      format.html { redirect_to twits_url, notice: 'Twit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_twit
      @twit = Twit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def twit_params
      params.require(:twit).permit(:content, :user_id)
    end
end

hometasks/lesson15/twitter/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      parameters = params.require(:user).permit(:nickname, :email, :avatar)

      if parameters['avatar'].empty?
        parameters['avatar'] = 'https://robohash.org/' + parameters['nickname']
      end

      parameters
    end
end

hometasks/lesson15/twitter/app/helpers/application_helper.rb
module ApplicationHelper
end

hometasks/lesson15/twitter/app/helpers/comments_helper.rb
module CommentsHelper
end

hometasks/lesson15/twitter/app/helpers/main_helper.rb
module MainHelper
end

hometasks/lesson15/twitter/app/helpers/tags_helper.rb
module TagsHelper
end

hometasks/lesson15/twitter/app/helpers/twits_helper.rb
module TwitsHelper
end

hometasks/lesson15/twitter/app/helpers/users_helper.rb
module UsersHelper
end

hometasks/lesson15/twitter/app/views/comments/_comment.html.erb
<p>
  <strong>Commenter:</strong>
  <%= comment.user.nickname %>
</p>

<p>
  <strong>Comment:</strong>
  <%= comment.body %>
</p>

<p>
  <%= link_to 'Destroy Comment', [comment.twit, comment],
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
</p>

<br>

hometasks/lesson15/twitter/app/views/comments/_form.html.erb
<%= form_for([@twit, @twit.comments.build]) do |f| %>
    <p>
      <%= f.label :user_id %><br>
      <%= f.collection_select :user_id, User.all, :id, :nickname, prompt: true %>
    </p>
    <p>
      <%= f.label :body %><br>
      <%= f.text_area :body %>
    </p>
    <p>
      <%= f.submit %>
    </p>
<% end %>

hometasks/lesson15/twitter/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= tag('meta', charset: 'utf-8') %>
  <%= tag('meta', 'http-equiv': 'X-UA-Compatible', content: 'IE=edge') %>
  <%= tag('meta', name: 'viewport', content: 'width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no') %>
  <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
  <title>Twitter</title>

  <!-- Bootstrap -->
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css' %>

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <%= javascript_include_tag 'https://cdn.jsdelivr.net/html5shiv/3.7.3/html5shiv.min.js' %>
  <%= javascript_include_tag 'https://cdn.jsdelivr.net/respond/1.4.2/respond.min.js' %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js' %>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<%= javascript_include_tag 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js' %>
</body>
</html>

hometasks/lesson15/twitter/app/views/main/index.html.erb
<%= render '/navigation' %>

hometasks/lesson15/twitter/app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tag_id %><br>
    <%= f.select :parent_id, nested_set_options(Tag, @tag) {|i| "#{'-' * i.level} #{i.name}" } %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hometasks/lesson15/twitter/app/views/tags/index.html.erb
<%= render '/navigation' %>

<div class="container">
  <p id="notice"><%= notice %></p>

  <h3>Tags</h3>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Name</th>
        <th>Parent</th>
        <th>&nbsp;</th>
      </tr>
    </thead>

    <tbody>
      <% @tags.each do |tag| %>
        <tr>
          <td><%= tag.name %></td>
          <td><%= tag.parent_id %></td>
          <td>
            <%= link_to 'Show', tag %> |
            <%= link_to 'Edit', edit_tag_path(tag) %> |
            <%= link_to 'Delete', tag, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Tag', new_tag_path %>
</div>

hometasks/lesson15/twitter/app/views/tags/new.html.erb
<%= render '/navigation' %>

<div class="container">
  <h3>New Tag</h3>

  <%= render 'form' %>

  <%= link_to 'Back', users_path %>
</div>

hometasks/lesson15/twitter/app/views/twits/_form.html.erb
<%= form_for(@twit) do |f| %>
  <% if @twit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@twit.errors.count, "error") %> prohibited this twit from being saved:</h2>

      <ul>
      <% @twit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.collection_select :user_id, User.all, :id, :nickname, prompt: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hometasks/lesson15/twitter/app/views/twits/edit.html.erb
<%= render '/navigation' %>

<div class="container">
  <h1>Editing Twit</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @twit %> |
  <%= link_to 'Back', twits_path %>
</div>

hometasks/lesson15/twitter/app/views/twits/index.html.erb
<%= render '/navigation' %>

<div class="container">
  <p id="notice"><%= notice %></p>

  <h3>Twits</h3>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Content</th>
        <th>User</th>
        <th>&nbsp;</th>
      </tr>
    </thead>

    <tbody>
      <% @twits.each do |twit| %>
        <tr>
          <td><%= twit.content %></td>
          <td><%= twit.user.nickname %></td>
          <td>
            <%= link_to 'Show', twit %> |
            <%= link_to 'Edit', edit_twit_path(twit) %> |
            <%= link_to 'Delete', twit, method: :delete, data: { confirm: 'Are you sure?' } %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Twit', new_twit_path %>
</div>

hometasks/lesson15/twitter/app/views/twits/new.html.erb
<%= render '/navigation' %>

<div class="container">
  <h3>New Twit</h3>

  <%= render 'form' %>

  <%= link_to 'Back', twits_path %>
</div>

hometasks/lesson15/twitter/app/views/twits/show.html.erb
<%= render '/navigation' %>

<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Content:</strong>
    <%= @twit.content %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @twit.user.nickname %>
  </p>

  <h2>Comments:</h2>
  <% if @twit.comments.any? %>
      <%= render @twit.comments %>
  <% else %>
      <p>No comments</p>
  <% end %>

  <h2>Add a comment:</h2>
  <%= render 'comments/form' %>

  <%= link_to 'Edit', edit_twit_path(@twit) %> |
  <%= link_to 'Back', twits_path %>
</div>

hometasks/lesson15/twitter/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %><br>
    <%= f.text_field :nickname %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>
  <div class="field">
    <%= f.label :avatar %><br>
    <%= f.text_field :avatar %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hometasks/lesson15/twitter/app/views/users/edit.html.erb
<%= render '/navigation' %>

<div class="container">
  <h3>Editing User</h3>

  <%= render 'form' %>

  <%= link_to 'Show', @user %> |
  <%= link_to 'Back', users_path %>
</div>

hometasks/lesson15/twitter/app/views/users/index.html.erb
<%= render '/navigation' %>

<div class="container">
  <div class="row">
    <div class="users-list-container col-md-9">
      <p id="notice"><%= notice %></p>

      <h3>Users</h3>

      <table class="table table-striped table-hover users-table">
        <thead>
        <tr>
          <th>User</th>
          <th>Email</th>
          <th>&nbsp;</th>
        </tr>
        </thead>

        <tbody>
        <% @users.each do |user| %>
            <tr>
              <td>
                <div class="table-cell-inner">
                  <%= link_to image_tag(user.avatar + '?size=36x36', class: "avatar")+content_tag(:div, content_tag(:span, user.nickname, class: "nick-name"), class: "nick-name-wrapper"), user, class: "user-link" %>
                </div>
              </td>
              <td><%= user.email %></td>
              <td>
                <%= link_to '', edit_user_path(user), class: "action edit", data: {toggle: 'tooltip', placement: 'top'}, title: "Edit" %>
                <%= link_to '', user, method: :delete, data: {confirm: 'Are you sure?', toggle: 'tooltip', placement: 'top'}, class: "action delete", title: "Delete" %>
              </td>
            </tr>
        <% end %>
        </tbody>
      </table>

      <br>

      <%= link_to 'New User', new_user_path %>
    </div>
  </div>
</div>

hometasks/lesson15/twitter/app/views/users/new.html.erb
<%= render '/navigation' %>

<div class="container">
  <h3>New User</h3>

  <%= render 'form' %>

  <%= link_to 'Back', users_path %>
</div>

hometasks/lesson15/twitter/app/views/users/show.html.erb
<%= render '/navigation' %>

<div class="container">
  <p id="notice"><%= notice %></p>

  <p>
    <strong>Nickname:</strong>
    <%= @user.nickname %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= @user.email %>
  </p>

  <p>
    <strong>Avatar:</strong>
    <%= @user.avatar %>
  </p>

  <%= link_to 'Edit', edit_user_path(@user) %> |
  <%= link_to 'Back', users_path %>
</div>